name: TotalWarArmyPlanner

services:
  frontend:
    container_name: frontend_container
    depends_on:
      - backend
#    image: pholm15/TWAP-frontend:latest
    build:
      context: .
      dockerfile: Dockerfile_frontend
    ports:
      - "5000:5000"
    environment:
      - BACKEND_DNS=backend

  backend:
    container_name: backend_container
    depends_on:
      - database
#    image: pholm15/TWAP-backend:latest
    build:
      context: .
      dockerfile: Dockerfile_backend
    ports:
      - "9000:9000"
    environment:
      - DB_DNS=database

  reverse_proxy:
    image: nginx:latest
    container_name: nginx_container
    depends_on:
      - frontend
    ports:
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cert.pem:/etc/nginx/ssl/fullchain.pem:ro
      - ./key.pem:/etc/nginx/ssl/privkey.pem:ro

  database:
    image: mongo:8.0
    container_name: database_container
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ROOT_PASSWORD
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb

networks:
  default:
    driver: bridge

volumes:
  mongo-data:
    driver: local
  mongo-config:
    driver: local